<?php

declare(strict_types=1);

/**
 * This file is part of Daycry Auth.
 *
 * (c) Daycry <daycry9@proton.me>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

namespace Tests\Controllers;

use CodeIgniter\Test\ControllerTestTrait;
use CodeIgniter\Test\DatabaseTestTrait;
use Config\Services;
use Daycry\Auth\Config\Auth;
use Daycry\Auth\Controllers\OauthController;
use Daycry\Auth\Libraries\Oauth\OauthManager;
use Mockery;
use Tests\Support\TestCase;

/**
 * @internal
 */
final class OauthControllerTest extends TestCase
{
    use ControllerTestTrait;
    use DatabaseTestTrait;

    protected $refresh   = true;
    protected $namespace = 'Daycry\Auth';

    protected function setUp(): void
    {
        parent::setUp();

        // Load Routes
        $routes = Services::routes();
        $auth   = new \Daycry\Auth\Auth(config('Auth'));
        $auth->routes($routes);
        Services::injectMock('routes', $routes);
    }

    public function testRedirectRedirectsToProviderUrl(): void
    {
        // Mock Oauth Config
        // $config = new Auth();
        // $config->providers['mock_provider'] = [
        //     'clientId'     => 'test_id',
        //     'clientSecret' => 'test_secret',
        //     'redirectUri'  => 'http://localhost/callback',
        //     'urlAuthorize'   => 'https://provider.com/oauth2/authorize',
        //     'urlAccessToken' => 'https://provider.com/oauth2/token',
        //     'urlResourceOwnerDetails' => 'https://provider.com/user',
        // ];

        // Mock the OauthManager
        $managerMock = Mockery::mock(OauthManager::class);
        $managerMock->shouldReceive('setProvider')->with('mock_provider')->andReturnSelf();
        $managerMock->shouldReceive('redirect')->andReturn(redirect()->to('https://provider.com/oauth2/authorize'));

        // Inject the mock?
        // Since OauthController instantiates OauthManager directly via `new`, we can't easily mock it without refactoring or using overloads.
        // However, for this test, we might need to rely on the actual implementation but mock the underlying Library if possible.
        // Or assume the Controller logic is simple enough to test integration style if we can control the config.

        // Let's actually test the real flow but with a mocked provider handling in OauthManager?
        // OauthManager uses `league/oauth2-client` GenericProvider.
        // Let's switch strategy: Test the Controller but knowing it uses the real Manager properly configured.

        // Setup Route
        // $this->withRoutes([
        //     ['get', 'oauth/login/(:segment)', 'Daycry\Auth\Controllers\OauthController::redirect/$1']
        // ]);

        // We can't easily mock `new OauthManager` inside the controller without a Factory or DI.
        // But `OauthManager` uses `Config\Oauth`. If we set `Config\Oauth` to have a provider, `GenericProvider` will be created.
        // When `redirect()` is called on GenericProvider, it returns a RedirectResponse.

        // Let's inject a Mock Config

        $config                            = config('Auth');
        $config->providers['testprovider'] = [
            'clientId'                => 'demoapp',
            'clientSecret'            => 'demopass',
            'redirectUri'             => 'http://example.com/your-redirect-url/',
            'urlAuthorize'            => 'http://example.com/oauth/authorize',
            'urlAccessToken'          => 'http://example.com/oauth/token',
            'urlResourceOwnerDetails' => 'http://example.com/api/user',
        ];

        $result = $this->controller(OauthController::class)
            ->execute('redirect', 'testprovider');

        $this->assertTrue($result->isRedirect());
        // The URL is generated by the provider, containing state etc.
        $headers  = $result->response()->headers();
        $location = $headers['Location']->getValue();

        $this->assertStringContainsString('http://example.com/oauth/authorize', (string) $location);
        $this->assertStringContainsString('client_id=demoapp', (string) $location);
    }
}
