<?= $this->extend(config('Auth')->views['layout']) ?>

<?= $this->section('title') ?><?= lang('Auth.totpSetupTitle') ?> <?= $this->endSection() ?>

<?= $this->section('main') ?>

<?php
/**
 * Variables expected:
 *   @var string $otpAuthUrl   The otpauth:// URL to encode as QR
 *   @var string $secret       The base32 secret for manual entry
 *   @var string $qrCodeUrl    A QR code image URL (optional, generated by TOTP::getQRCodeUrl)
 */
?>

<div class="container d-flex justify-content-center p-5">
    <div class="card col-12 col-md-6 shadow-sm">
        <div class="card-body">
            <h5 class="card-title mb-4"><?= lang('Auth.totpSetupTitle') ?></h5>

            <p><?= lang('Auth.totpSetupIntro') ?></p>

            <?php if (session('error') !== null) : ?>
                <div class="alert alert-danger"><?= esc(session('error')) ?></div>
            <?php endif ?>

            <!-- QR Code -->
            <div class="text-center my-4">
                <img src="<?= esc($qrCodeUrl) ?>" alt="<?= lang('Auth.totpQrAlt') ?>" width="200" height="200">
            </div>

            <!-- Manual entry key -->
            <p class="text-center text-muted small"><?= lang('Auth.totpManualKey') ?></p>
            <div class="text-center mb-4">
                <code class="fs-6 user-select-all"><?= esc(chunk_split($secret, 4, ' ')) ?></code>
            </div>

            <!-- Confirmation form: user enters a code to prove scanning worked -->
            <hr>
            <p class="mt-3"><?= lang('Auth.totpSetupConfirmIntro') ?></p>

            <form action="<?= esc($confirmUrl ?? url_to('totp-setup-confirm')) ?>" method="post">
                <?= csrf_field() ?>

                <div class="mb-3">
                    <label for="token" class="form-label"><?= lang('Auth.totpEnterCode') ?></label>
                    <input type="number" id="token" class="form-control" name="token"
                        placeholder="000000" inputmode="numeric" pattern="[0-9]*"
                        autocomplete="one-time-code" minlength="6" maxlength="6"
                        required autofocus>
                </div>

                <div class="d-grid">
                    <button type="submit" class="btn btn-primary"><?= lang('Auth.totpSetupActivate') ?></button>
                </div>
            </form>
        </div>
    </div>
</div>

<?= $this->endSection() ?>
